export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const LOGOUT = 'LOGOUT';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const GET_RESET_PASSWORD_TOKEN = 'GET_RESET_PASSWORD_TOKEN';
export const EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED';

export const SET_ONLINE_USERS = 'SET_ONLINE_USERS';
export const SET_USER_ONLINE = 'SET_USER_ONLINE';
export const SET_USER_OFFLINE = 'SET_USER_OFFLINE';
