name: Run Jest
on:
  pull_request:
    branches:
    - main
    - master
    - feature/*
    - test/*
    - component/*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.17.0'
      - run: npm install
      - run: npm test
